lists/urls.py
from django.conf.urls import url

from lists import views


urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlist/urls.py
from django.conf.urls import include, url

from lists import views as list_views
from lists import urls as list_urls


urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.core.urlresolvers import reverse
from django.db import models


class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='')
    parent_list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('parent_list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item

BLANK_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do- item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': BLANK_ITEM_ERROR}
        }

    def save(self, for_list):
        self.instance.parent_list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.parent_list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

lists/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, render

from lists.forms import (
    BLANK_ITEM_ERROR, DUPLICATE_ITEM_ERROR,
    ExistingListItemForm, ItemForm
)
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        parent_list = List.objects.create()
        form.save(for_list=parent_list)
        return redirect(parent_list)
    else:
        return render(request, 'home.html', {'form': form})


def view_list(request, list_id):
    this_list = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=this_list)

    if request.method == 'POST':
        form = ExistingListItemForm(
            for_list=this_list,
            data=request.POST
        )
        if form.is_valid():
            form.save()
            return redirect(this_list)

    return render(
        request,
        'list.html',
        {'parent_list': this_list, 'form': form}
    )

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>

        <!-- Bootstrap -->
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock%}</h1>
                        <form method="post" action="{% block form_action %}{% endblock %}">
                            {% csrf_token %}
                            {{ form.text }}
                            {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block">{{ form.text.errors }}</span>
                            </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="{% static 'lists.js' %}"></script>
        <script>
            $(function() {
                window.Superlist.initialize();
            });
        </script>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a To-Do List{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do List{% endblock %}

{% block form_action %}/lists/{{ parent_list.id }}/{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in parent_list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
</table>
{% endblock %}